name: Deploy to heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15',
          check-latest: true
      - run: yarn install --production=false
      - run: yarn build
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'ojitos-tapatios-back'
          heroku_email: 'uramirez0@ucol.mx'
          remote_branch: main # <- Include this
          appdir: "dist"
